# Generated by Django 6.0.3 on 2026-03-17 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='income',
            name='label',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.AddField(
            model_name='expense',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MORTGAGE', 'Mortgage'), ('INSURANCE', 'Insurances (Car/Life/House)'), ('UTILITIES', 'Utilities (Gas/Water/Elec)'), ('SUBSCRIPTIONS', 'Subscriptions (Netflix/Spotify)'), ('GROCERIES', 'Groceries'), ('DEBTS', 'Debts'), ('FUEL', 'Fuel/Transport'), ('LOANS', 'Loans / Car Finance'), ('OTHERS', 'Others / One-off Payments')], default='OTHERS', max_length=20),
        ),
    ]
