# Generated by Django 6.0.3 on 2026-04-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_expense_user_remove_income_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MORTGAGE', 'Mortgage'), ('INSURANCE', 'Insurances (Car/Life/House)'), ('UTILITIES', 'Utilities (Gas/Water/Elec)'), ('SUBSCRIPTIONS', 'Subscriptions (Netflix/Spotify)'), ('GROCERIES', 'Groceries'), ('DEBTS', 'Debts'), ('FUEL', 'Fuel / Transport'), ('LOANS', 'Loans / Car Finance'), ('MOBILE', 'Mobile / Phone'), ('OTHERS', 'Others / One-off Payments')], default='OTHERS', max_length=20),
        ),
    ]
