# Generated by Django 6.0.3 on 2026-04-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense_user_income_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='customer_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUALLY', 'Annually')], default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='tariff_details',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MORTGAGE', 'Mortgage'), ('INSURANCE', 'Insurances (Car/Life/House)'), ('UTILITIES', 'Utilities (Gas/Water/Elec)'), ('SUBSCRIPTIONS', 'Subscriptions (Netflix/Spotify)'), ('GROCERIES', 'Groceries'), ('DEBTS', 'Debts'), ('FUEL', 'Fuel / Transport'), ('LOANS', 'Loans / Car Finance'), ('MOBILE', 'Mobile / Phone'), ('SAVINGS', 'Savings'), ('INVESTMENTS', 'Investments'), ('OTHERS', 'Others / One-off Payments')], default='OTHERS', max_length=20),
        ),
    ]
