# Generated by Django 6.0.3 on 2026-04-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expense_customer_number_expense_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bill_type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('VARIABLE', 'Variable')], default='FIXED', max_length=10),
        ),
    ]
