# Generated by Django 6.0.3 on 2026-05-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_savingsgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expense',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('INS_CAR', 'Car Insurance'), ('INS_HOME', 'Home Insurance'), ('INS_LIFE', 'Life Insurance'), ('INS_HEALTH', 'Health Insurance'), ('INS_TRAVEL', 'Travel Insurance'), ('INS_PET', 'Pet Insurance'), ('INS_OTHER', 'Other Insurance'), ('LOAN_PERSONAL', 'Personal Loan'), ('LOAN_CAR', 'Car Finance'), ('LOAN_STUDENT', 'Student Loan'), ('LOAN_PAYDAY', 'Payday Loan'), ('LOAN_OTHER', 'Other Loan'), ('DEBT_CREDIT', 'Credit Card'), ('DEBT_OVERDRAFT', 'Overdraft'), ('DEBT_BNPL', 'Buy Now Pay Later'), ('DEBT_OTHER', 'Other Debt'), ('SUB_STREAMING', 'Streaming (Netflix/Disney)'), ('SUB_MUSIC', 'Music (Spotify/Apple)'), ('SUB_GAMING', 'Gaming'), ('SUB_SOFTWARE', 'Software/Apps'), ('SUB_GYM', 'Gym / Fitness'), ('SUB_OTHER', 'Other Subscription'), ('UTIL_GAS', 'Gas'), ('UTIL_ELECTRIC', 'Electricity'), ('UTIL_WATER', 'Water'), ('UTIL_COUNCIL', 'Council Tax'), ('UTIL_BROADBAND', 'Broadband'), ('UTIL_OTHER', 'Other Utility')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='income',
            name='is_recurring',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='income',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='income',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MORTGAGE', 'Mortgage'), ('INSURANCE', 'Insurance'), ('UTILITIES', 'Utilities (Gas/Water/Elec)'), ('SUBSCRIPTIONS', 'Subscriptions'), ('GROCERIES', 'Groceries'), ('DEBTS', 'Debts'), ('FUEL', 'Fuel / Transport'), ('LOANS', 'Loans / Car Finance'), ('MOBILE', 'Mobile / Phone'), ('SAVINGS', 'Savings'), ('INVESTMENTS', 'Investments'), ('OTHERS', 'Others / One-off Payments')], default='OTHERS', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUALLY', 'Annually'), ('ONE_OFF', 'One-off')], default='MONTHLY', max_length=10),
        ),
    ]
