# Generated by Django 6.0.3 on 2026-09-01 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
